### ISSUE TITLE
Add .gitignore and gather files into different folders

### ISSUE THREAD

**Issue by wenh06** [johnperry-math/mew_cats#3]
Intermediate files like `.blg` files can be ignored via a `.gitignore` file. And perhaps the project could be better structured by gathering files of different topics into corresponding folders.

**Comment by johnperry-math** [comment]
Can you elaborate on "files of different topics"? The graphics folder is in fact in different topics, so do you mean splitting up the main file (`draft(x).lyx`) into separate files?

**Comment by wenh06** [comment]
> Can you elaborate on "files of different topics"? The graphics folder is in fact in different topics, so do you mean splitting up the main file (`draft(x).lyx`) into separate files?

Maybe the older versions (in my understanding) could be gathered into some `legacy` folder?

**Comment by johnperry-math** [comment]
Thank you; that's a good idea. In fact, I really ought to remove a lot of the accumulated cruft. I've done that now -- well, I haven't added a `.gitignore`, because I don't think that's strictly necessary; I just removed those auxiliary files, which I had added once for a coauthor or another user I know personally, can't recall.
